-- ==========================================
-- HYDRA CLOUD & HYDRA PRIME STREAMING - SCHEMA COMPLETO FINAL v7 CON RLS
-- + SISTEMA ANTI-FILTREO DE TABLAS EN EL INSPECTOR
-- ==========================================
-- Servidor #2:  https://gwibpxgibmraqebetvss.supabase.co
--
-- CAMBIOS v7 (idempotente + fixes):
--  * DROP POLICY IF EXISTS antes de cada CREATE POLICY  -> re-ejecutable sin el
--    error 42710 "policy ... already exists".
--  * Fix recursión infinita en collab_members (helper is_group_member DEFINER).
--  * Fix collab_presence: política de lectura para ver usuarios conectados.
--  * ENABLE RLS movido al FINAL (sección 27) para cubrir todas las tablas
--    incluso en una base nueva (antes quedaban sin RLS en la 1ª corrida).
--  * Helpers request.jwt.claims con missing_ok (no revientan en el SQL editor).
-- ==========================================

-- ==========================================
-- 0. HELPERS NECESARIOS TEMPRANO (los usa el RLS de más abajo)
-- ==========================================
-- plpgsql para diferir la validación del cuerpo (las tablas se crean después).
-- DROP FUNCTION antes de cada una: si ya existían con OTRO nombre de parámetro,
-- CREATE OR REPLACE falla con 42P13 "cannot change name of input parameter".
DROP FUNCTION IF EXISTS current_user_email();
DROP FUNCTION IF EXISTS is_admin();
DROP FUNCTION IF EXISTS is_group_member(BIGINT);
DROP FUNCTION IF EXISTS is_project_member(BIGINT);

-- Email del usuario actual (del JWT de Firebase reenviado por el cliente).
CREATE OR REPLACE FUNCTION current_user_email()
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER STABLE
AS $$
BEGIN
    RETURN current_setting('request.jwt.claims', true)::json->>'email';
END;
$$;

-- ¿El usuario es admin?
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER STABLE
AS $$
BEGIN
    RETURN current_setting('request.jwt.claims', true)::json->>'role' = 'admin';
END;
$$;

-- ¿El usuario es miembro (o dueño) de un grupo de Hydra Team?
-- SECURITY DEFINER: consulta collab_members SIN aplicar su RLS -> evita la
-- recursión infinita que ocurre si la política de collab_members se consulta a
-- sí misma.
CREATE OR REPLACE FUNCTION is_group_member(gid BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER STABLE
AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM collab_members
        WHERE collab_members.group_id = gid
          AND collab_members.user_email = current_setting('request.jwt.claims', true)::json->>'email'
    );
END;
$$;

-- ¿El usuario es miembro (o dueño) de un proyecto de Hydra Cloud?
CREATE OR REPLACE FUNCTION is_project_member(pid BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER STABLE
AS $$
DECLARE
    uemail TEXT;
BEGIN
    uemail := current_setting('request.jwt.claims', true)::json->>'email';
    RETURN EXISTS (
        SELECT 1 FROM project_members
        WHERE project_members.project_id = pid
          AND project_members.user_email = uemail
    ) OR EXISTS (
        SELECT 1 FROM cloud_projects
        WHERE cloud_projects.id = pid
          AND cloud_projects.user_email = uemail
    );
END;
$$;

-- ==========================================
-- 1. cloud_projects
-- ==========================================
CREATE TABLE IF NOT EXISTS cloud_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    user_email TEXT NOT NULL,
    project_name TEXT NOT NULL,
    project_type TEXT NOT NULL,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleted', 'provisioning')),
    region TEXT DEFAULT 'us-east-1',
    compute_size TEXT DEFAULT 'micro',
    storage_gb INTEGER DEFAULT 1,
    connection_string TEXT
);

DROP POLICY IF EXISTS "Users can view own projects" ON cloud_projects;
CREATE POLICY "Users can view own projects" ON cloud_projects
    FOR SELECT USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
        OR
        current_setting('request.jwt.claims')::json->>'role' = 'admin'
    );

DROP POLICY IF EXISTS "Users can insert own projects" ON cloud_projects;
CREATE POLICY "Users can insert own projects" ON cloud_projects
    FOR INSERT WITH CHECK (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

DROP POLICY IF EXISTS "Users can update own projects" ON cloud_projects;
CREATE POLICY "Users can update own projects" ON cloud_projects
    FOR UPDATE USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

DROP POLICY IF EXISTS "Users can delete own projects" ON cloud_projects;
CREATE POLICY "Users can delete own projects" ON cloud_projects
    FOR DELETE USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

-- ==========================================
-- 2. deployments
-- ==========================================
CREATE TABLE IF NOT EXISTS deployments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    user_email TEXT NOT NULL,
    deployment_status TEXT DEFAULT 'pending' CHECK (deployment_status IN ('pending', 'running', 'success', 'failed')),
    commit_hash TEXT,
    logs TEXT
);

DROP POLICY IF EXISTS "Users can view own deployments" ON deployments;
CREATE POLICY "Users can view own deployments" ON deployments
    FOR SELECT USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
        OR EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = deployments.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

DROP POLICY IF EXISTS "Users can insert own deployments" ON deployments;
CREATE POLICY "Users can insert own deployments" ON deployments
    FOR INSERT WITH CHECK (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

-- ==========================================
-- 3. project_tables
-- ==========================================
CREATE TABLE IF NOT EXISTS project_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    table_name TEXT NOT NULL,
    description TEXT
);

DROP POLICY IF EXISTS "Users can manage tables of own projects" ON project_tables;
CREATE POLICY "Users can manage tables of own projects" ON project_tables
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_tables.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- 4. project_auth_users
-- ==========================================
CREATE TABLE IF NOT EXISTS project_auth_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    provider TEXT DEFAULT 'email',
    last_sign_in_at TIMESTAMPTZ DEFAULT NOW()
);

DROP POLICY IF EXISTS "Users can manage auth users of own projects" ON project_auth_users;
CREATE POLICY "Users can manage auth users of own projects" ON project_auth_users
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_auth_users.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- 5. project_auth_providers
-- ==========================================
CREATE TABLE IF NOT EXISTS project_auth_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    provider_name TEXT NOT NULL,
    enabled BOOLEAN DEFAULT false,
    CONSTRAINT unique_project_provider UNIQUE (project_id, provider_name)
);

DROP POLICY IF EXISTS "Users can manage auth providers of own projects" ON project_auth_providers;
CREATE POLICY "Users can manage auth providers of own projects" ON project_auth_providers
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_auth_providers.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- 6. project_auth_policies
-- ==========================================
CREATE TABLE IF NOT EXISTS project_auth_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    policy_name TEXT NOT NULL,
    table_name TEXT NOT NULL,
    operation TEXT DEFAULT 'SELECT',
    definition TEXT
);

DROP POLICY IF EXISTS "Users can manage auth policies of own projects" ON project_auth_policies;
CREATE POLICY "Users can manage auth policies of own projects" ON project_auth_policies
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_auth_policies.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- 7. project_storage_buckets
-- ==========================================
CREATE TABLE IF NOT EXISTS project_storage_buckets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    bucket_name TEXT NOT NULL
);

DROP POLICY IF EXISTS "Users can manage storage buckets of own projects" ON project_storage_buckets;
CREATE POLICY "Users can manage storage buckets of own projects" ON project_storage_buckets
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_storage_buckets.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- 8. project_storage_policies
-- ==========================================
CREATE TABLE IF NOT EXISTS project_storage_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    policy_name TEXT NOT NULL,
    bucket_name TEXT NOT NULL,
    operation TEXT DEFAULT 'SELECT',
    definition TEXT
);

DROP POLICY IF EXISTS "Users can manage storage policies of own projects" ON project_storage_policies;
CREATE POLICY "Users can manage storage policies of own projects" ON project_storage_policies
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_storage_policies.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- 9. project_members
-- ==========================================
CREATE TABLE IF NOT EXISTS project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    user_email TEXT NOT NULL,
    role TEXT DEFAULT 'member',
    CONSTRAINT unique_project_member UNIQUE (project_id, user_email)
);

DROP POLICY IF EXISTS "Members can view project members" ON project_members;
CREATE POLICY "Members can view project members" ON project_members
    FOR SELECT USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
        OR EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_members.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

DROP POLICY IF EXISTS "Project owners can manage members" ON project_members;
CREATE POLICY "Project owners can manage members" ON project_members
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_members.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- 10. project_invitations
-- ==========================================
CREATE TABLE IF NOT EXISTS project_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    invited_email TEXT NOT NULL,
    invited_by TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined'))
);

DROP POLICY IF EXISTS "Project owners can manage invitations" ON project_invitations;
CREATE POLICY "Project owners can manage invitations" ON project_invitations
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_invitations.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

DROP POLICY IF EXISTS "Users can view their own invitations" ON project_invitations;
CREATE POLICY "Users can view their own invitations" ON project_invitations
    FOR SELECT USING (
        invited_email = current_setting('request.jwt.claims')::json->>'email'
    );

-- ==========================================
-- 11. hydra_api_keys
-- ==========================================
CREATE TABLE IF NOT EXISTS hydra_api_keys (
    id SERIAL PRIMARY KEY,
    user_email TEXT NOT NULL,
    name TEXT NOT NULL,
    api_key TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_used TIMESTAMP WITH TIME ZONE
);

DROP POLICY IF EXISTS "Users can manage own API keys" ON hydra_api_keys;
CREATE POLICY "Users can manage own API keys" ON hydra_api_keys
    FOR ALL USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

-- ==========================================
-- 12-13. project_edge_functions & logs
-- ==========================================
CREATE TABLE IF NOT EXISTS project_edge_functions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    function_name TEXT NOT NULL,
    deployment_url TEXT,
    status TEXT DEFAULT 'active'
);

DROP POLICY IF EXISTS "Users can manage edge functions of own projects" ON project_edge_functions;
CREATE POLICY "Users can manage edge functions of own projects" ON project_edge_functions
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_edge_functions.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

CREATE TABLE IF NOT EXISTS project_edge_function_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    function_id BIGINT REFERENCES project_edge_functions(id) ON DELETE CASCADE,
    log_message TEXT NOT NULL
);

DROP POLICY IF EXISTS "Users can view edge function logs of own projects" ON project_edge_function_logs;
CREATE POLICY "Users can view edge function logs of own projects" ON project_edge_function_logs
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_edge_function_logs.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- TABLAS PARA EL HISTORIAL DE HYDRA PRIME
-- ==========================================
CREATE TABLE IF NOT EXISTS user_streaming_profiles (
    user_email TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    preferred_server TEXT DEFAULT 'UNLIMPLAY',
    theme TEXT DEFAULT 'dark'
);

DROP POLICY IF EXISTS "Users can manage own streaming profile" ON user_streaming_profiles;
CREATE POLICY "Users can manage own streaming profile" ON user_streaming_profiles
    FOR ALL USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

CREATE TABLE IF NOT EXISTS user_watch_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    item_id TEXT NOT NULL,
    item_data JSONB NOT NULL,
    watched_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_history_item UNIQUE (user_email, item_id)
);

DROP POLICY IF EXISTS "Users can manage own watch history" ON user_watch_history;
CREATE POLICY "Users can manage own watch history" ON user_watch_history
    FOR ALL USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

CREATE TABLE IF NOT EXISTS user_continue_watching (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    item_id TEXT NOT NULL,
    item_data JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_continue_item UNIQUE (user_email, item_id)
);

DROP POLICY IF EXISTS "Users can manage own continue watching" ON user_continue_watching;
CREATE POLICY "Users can manage own continue watching" ON user_continue_watching
    FOR ALL USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

CREATE TABLE IF NOT EXISTS user_my_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    item_id TEXT NOT NULL,
    item_data JSONB NOT NULL,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_mylist_item UNIQUE (user_email, item_id)
);

DROP POLICY IF EXISTS "Users can manage own my list" ON user_my_list;
CREATE POLICY "Users can manage own my list" ON user_my_list
    FOR ALL USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

CREATE TABLE IF NOT EXISTS user_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    item_id TEXT NOT NULL,
    item_data JSONB NOT NULL,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_reminder_item UNIQUE (user_email, item_id)
);

DROP POLICY IF EXISTS "Users can manage own reminders" ON user_reminders;
CREATE POLICY "Users can manage own reminders" ON user_reminders
    FOR ALL USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

-- ==========================================
-- 14. MARKETPLACE DE EXTENSIONES
-- ==========================================
CREATE TABLE IF NOT EXISTS extensions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    ext_id          TEXT UNIQUE NOT NULL,
    name            TEXT NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    readme          TEXT DEFAULT '',
    category        TEXT DEFAULT 'Otros',
    version         TEXT DEFAULT '1.0.0',
    icon_url        TEXT,
    code            TEXT DEFAULT '',
    author_user_id  TEXT,
    author_email    TEXT,
    author_username TEXT,
    installs        INTEGER DEFAULT 0,
    rating          NUMERIC DEFAULT 5,
    is_published    BOOLEAN DEFAULT TRUE
);

DROP POLICY IF EXISTS "Anyone can view published extensions" ON extensions;
CREATE POLICY "Anyone can view published extensions" ON extensions
    FOR SELECT USING (is_published = true);

DROP POLICY IF EXISTS "Authors can manage own extensions" ON extensions;
CREATE POLICY "Authors can manage own extensions" ON extensions
    FOR ALL USING (
        author_email = current_setting('request.jwt.claims')::json->>'email'
    );

DROP POLICY IF EXISTS "Admins can manage all extensions" ON extensions;
CREATE POLICY "Admins can manage all extensions" ON extensions
    FOR ALL USING (
        current_setting('request.jwt.claims')::json->>'role' = 'admin'
    );

-- Contador de instalaciones: SECURITY DEFINER para poder incrementar el contador
-- de una extensión ajena sin que el RLS lo bloquee (el IDE llama a este RPC).
DROP FUNCTION IF EXISTS increment_installs(TEXT);
CREATE OR REPLACE FUNCTION increment_installs(p_ext_id TEXT)
RETURNS void
LANGUAGE sql SECURITY DEFINER
AS $$
    UPDATE extensions SET installs = COALESCE(installs, 0) + 1 WHERE ext_id = p_ext_id;
$$;

-- ==========================================
-- 15. API REST DE PROYECTOS
-- ==========================================
CREATE TABLE IF NOT EXISTS project_api_config (
    project_id        BIGINT PRIMARY KEY REFERENCES cloud_projects(id) ON DELETE CASCADE,
    anon_key          TEXT NOT NULL,
    service_role_key  TEXT NOT NULL,
    api_url           TEXT NOT NULL,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);

DROP POLICY IF EXISTS "Users can manage API config of own projects" ON project_api_config;
CREATE POLICY "Users can manage API config of own projects" ON project_api_config
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_api_config.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

CREATE TABLE IF NOT EXISTS project_data (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL REFERENCES cloud_projects(id) ON DELETE CASCADE,
    table_name  TEXT NOT NULL,
    row_data    JSONB NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

DROP POLICY IF EXISTS "Project members can manage project data" ON project_data;
CREATE POLICY "Project members can manage project data" ON project_data
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM project_members
            WHERE project_members.project_id = project_data.project_id
            AND project_members.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
        OR EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_data.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- 16. SQL EDITOR GUARDADO EN SERVIDOR
-- ==========================================
CREATE TABLE IF NOT EXISTS project_sql_queries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL REFERENCES cloud_projects(id) ON DELETE CASCADE,
    name        TEXT NOT NULL DEFAULT 'untitled_query',
    query_text  TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

DROP POLICY IF EXISTS "Users can manage SQL queries of own projects" ON project_sql_queries;
CREATE POLICY "Users can manage SQL queries of own projects" ON project_sql_queries
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM cloud_projects
            WHERE cloud_projects.id = project_sql_queries.project_id
            AND cloud_projects.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
        OR EXISTS (
            SELECT 1 FROM project_members
            WHERE project_members.project_id = project_sql_queries.project_id
            AND project_members.user_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

-- ==========================================
-- 17. HYDRA TEAM · PROGRAMACIÓN EN EQUIPO
-- ==========================================
CREATE TABLE IF NOT EXISTS collab_presence (
    user_email  TEXT PRIMARY KEY,
    username    TEXT,
    photo_url   TEXT,
    status      TEXT DEFAULT 'online',
    last_seen   TIMESTAMPTZ DEFAULT NOW()
);

-- Cada quien gestiona SU propia presencia (heartbeat/upsert).
DROP POLICY IF EXISTS "Users can manage own presence" ON collab_presence;
CREATE POLICY "Users can manage own presence" ON collab_presence
    FOR ALL USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

-- FIX: cualquier usuario logueado puede LEER la presencia de otros (necesario
-- para "usuarios en línea" e invitar a Hydra Team). Sin esto, onlineUsers()
-- devolvía vacío porque solo veías tu propia fila.
DROP POLICY IF EXISTS "Logged users can view presence" ON collab_presence;
CREATE POLICY "Logged users can view presence" ON collab_presence
    FOR SELECT USING (
        current_setting('request.jwt.claims')::json->>'email' IS NOT NULL
    );

CREATE TABLE IF NOT EXISTS collab_groups (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    code           TEXT UNIQUE NOT NULL,
    name           TEXT NOT NULL DEFAULT 'Proyecto en equipo',
    owner_email    TEXT NOT NULL,
    owner_username TEXT,
    folder_name    TEXT,
    active         BOOLEAN DEFAULT TRUE
);

DROP POLICY IF EXISTS "Members can view groups" ON collab_groups;
CREATE POLICY "Members can view groups" ON collab_groups
    FOR SELECT USING (
        active = true AND is_group_member(id)
    );

DROP POLICY IF EXISTS "Owners can manage groups" ON collab_groups;
CREATE POLICY "Owners can manage groups" ON collab_groups
    FOR ALL USING (
        owner_email = current_setting('request.jwt.claims')::json->>'email'
    );

CREATE TABLE IF NOT EXISTS collab_members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    group_id    BIGINT NOT NULL REFERENCES collab_groups(id) ON DELETE CASCADE,
    user_email  TEXT NOT NULL,
    username    TEXT,
    role        TEXT DEFAULT 'member',
    status      TEXT DEFAULT 'invited',
    last_seen   TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_collab_member UNIQUE (group_id, user_email)
);

-- FIX recursión: antes esta política consultaba collab_members dentro de sí
-- misma -> "infinite recursion detected in policy". Ahora usa is_group_member()
-- (SECURITY DEFINER, sin RLS) o tu propia fila.
DROP POLICY IF EXISTS "Members can view group members" ON collab_members;
CREATE POLICY "Members can view group members" ON collab_members
    FOR SELECT USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
        OR is_group_member(group_id)
    );

DROP POLICY IF EXISTS "Owners can manage group members" ON collab_members;
CREATE POLICY "Owners can manage group members" ON collab_members
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM collab_groups
            WHERE collab_groups.id = collab_members.group_id
            AND collab_groups.owner_email = current_setting('request.jwt.claims')::json->>'email'
        )
    );

CREATE TABLE IF NOT EXISTS collab_files (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT NOT NULL REFERENCES collab_groups(id) ON DELETE CASCADE,
    path        TEXT NOT NULL,
    is_dir      BOOLEAN DEFAULT FALSE,
    content     TEXT DEFAULT '',
    deleted     BOOLEAN DEFAULT FALSE,
    updated_by  TEXT,
    updated_at  TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_collab_file UNIQUE (group_id, path)
);

DROP POLICY IF EXISTS "Members can manage group files" ON collab_files;
CREATE POLICY "Members can manage group files" ON collab_files
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM collab_members
            WHERE collab_members.group_id = collab_files.group_id
            AND collab_members.user_email = current_setting('request.jwt.claims')::json->>'email'
            AND collab_members.status = 'joined'
        )
    );

CREATE TABLE IF NOT EXISTS collab_runs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id         BIGINT NOT NULL REFERENCES collab_groups(id) ON DELETE CASCADE,
    started_by       TEXT NOT NULL,
    started_username TEXT,
    kind             TEXT DEFAULT 'web',
    url              TEXT,
    label            TEXT,
    active           BOOLEAN DEFAULT TRUE,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

DROP POLICY IF EXISTS "Members can view group runs" ON collab_runs;
CREATE POLICY "Members can view group runs" ON collab_runs
    FOR SELECT USING (
        is_group_member(group_id)
    );

DROP POLICY IF EXISTS "Members can start runs" ON collab_runs;
CREATE POLICY "Members can start runs" ON collab_runs
    FOR INSERT WITH CHECK (
        started_by = current_setting('request.jwt.claims')::json->>'email'
        AND is_group_member(group_id)
    );

-- ==========================================
-- 18. HYDRA SUPPORT · TICKETS Y CONFIGURACIÓN
-- ==========================================
CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id TEXT NOT NULL,
    channel_id TEXT NOT NULL,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    is_archived BOOLEAN DEFAULT FALSE,
    archived_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ
);

DROP POLICY IF EXISTS "Users can view own tickets" ON tickets;
CREATE POLICY "Users can view own tickets" ON tickets
    FOR SELECT USING (
        user_id = current_setting('request.jwt.claims')::json->>'email'
        OR current_setting('request.jwt.claims')::json->>'role' = 'admin'
    );

DROP POLICY IF EXISTS "Users can create tickets" ON tickets;
CREATE POLICY "Users can create tickets" ON tickets
    FOR INSERT WITH CHECK (
        user_id = current_setting('request.jwt.claims')::json->>'email'
    );

CREATE TABLE IF NOT EXISTS guild_config (
    guild_id TEXT PRIMARY KEY,
    support_role_id TEXT,
    log_channel_id TEXT,
    ticket_category_id TEXT,
    archive_category_id TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

DROP POLICY IF EXISTS "Admins can manage guild config" ON guild_config;
CREATE POLICY "Admins can manage guild config" ON guild_config
    FOR ALL USING (
        current_setting('request.jwt.claims')::json->>'role' = 'admin'
    );

-- ==========================================
-- 19. HYDRA BOTS
-- ==========================================
CREATE TABLE IF NOT EXISTS hydra_bots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    tags TEXT[] DEFAULT '{}',
    servers INTEGER DEFAULT 0,
    invite_url TEXT,
    author_email TEXT NOT NULL,
    author_username TEXT,
    photo_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    votes INTEGER DEFAULT 0
);

DROP POLICY IF EXISTS "Anyone can view active bots" ON hydra_bots;
CREATE POLICY "Anyone can view active bots" ON hydra_bots
    FOR SELECT USING (is_active = true);

DROP POLICY IF EXISTS "Authors can manage own bots" ON hydra_bots;
CREATE POLICY "Authors can manage own bots" ON hydra_bots
    FOR ALL USING (
        author_email = current_setting('request.jwt.claims')::json->>'email'
    );

DROP POLICY IF EXISTS "Admins can manage all bots" ON hydra_bots;
CREATE POLICY "Admins can manage all bots" ON hydra_bots
    FOR ALL USING (
        current_setting('request.jwt.claims')::json->>'role' = 'admin'
    );

-- ==========================================
-- 20. HYDRA UPDATES
-- ==========================================
CREATE TABLE IF NOT EXISTS hydra_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'web',
    update_type TEXT NOT NULL DEFAULT 'mejora',
    tags TEXT[] DEFAULT '{}',
    author_email TEXT NOT NULL DEFAULT 'hydrasoftwareoficial@gmail.com',
    is_published BOOLEAN DEFAULT TRUE
);

DROP POLICY IF EXISTS "Anyone can view published updates" ON hydra_updates;
CREATE POLICY "Anyone can view published updates" ON hydra_updates
    FOR SELECT USING (is_published = true);

DROP POLICY IF EXISTS "Admins can manage updates" ON hydra_updates;
CREATE POLICY "Admins can manage updates" ON hydra_updates
    FOR ALL USING (
        current_setting('request.jwt.claims')::json->>'role' = 'admin'
    );

-- ==========================================
-- 21. HYDRA AI · CONVERSACIONES Y AJUSTES
-- ==========================================
CREATE TABLE IF NOT EXISTS ai_conversations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    user_email      TEXT NOT NULL,
    conversation_id TEXT NOT NULL,
    title           TEXT DEFAULT 'Nueva conversación',
    messages        JSONB NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT unique_ai_conversation UNIQUE (user_email, conversation_id)
);

DROP POLICY IF EXISTS "Users can manage own AI conversations" ON ai_conversations;
CREATE POLICY "Users can manage own AI conversations" ON ai_conversations
    FOR ALL USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

CREATE TABLE IF NOT EXISTS hydra_ai_settings (
    user_email    TEXT PRIMARY KEY,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW(),
    system_prompt TEXT,
    preferences   JSONB DEFAULT '{}'::jsonb,
    ai_avatar_url TEXT
);

DROP POLICY IF EXISTS "Users can manage own AI settings" ON hydra_ai_settings;
CREATE POLICY "Users can manage own AI settings" ON hydra_ai_settings
    FOR ALL USING (
        user_email = current_setting('request.jwt.claims')::json->>'email'
    );

-- ==========================================
-- 22. SISTEMA ANTI-FILTREO DE TABLAS EN EL INSPECTOR
-- ==========================================
CREATE OR REPLACE FUNCTION hide_tables_from_inspector()
RETURNS void AS $$
DECLARE
    tbl RECORD;
BEGIN
    FOR tbl IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename IN (
        'project_api_config',
        'project_data',
        'hydra_api_keys',
        'project_auth_users',
        'project_auth_policies',
        'project_auth_providers',
        'project_storage_buckets',
        'project_storage_policies',
        'collab_files',
        'collab_members',
        'collab_groups',
        'collab_runs',
        'collab_presence',
        'tickets',
        'guild_config'
    ) LOOP
        EXECUTE format('COMMENT ON TABLE %I IS ''@hidden''', tbl.tablename);
    END LOOP;
END;
$$ LANGUAGE plpgsql;

SELECT hide_tables_from_inspector();

-- ==========================================
-- 24. STORAGE POLICIES PARA BUCKETS
-- ==========================================

-- Extension icons bucket
DROP POLICY IF EXISTS "ext_icons_select" ON storage.objects;
DROP POLICY IF EXISTS "ext_icons_insert" ON storage.objects;
DROP POLICY IF EXISTS "ext_icons_update" ON storage.objects;
DROP POLICY IF EXISTS "ext_icons_delete" ON storage.objects;

CREATE POLICY "ext_icons_select" ON storage.objects
    FOR SELECT USING (bucket_id = 'extension-icons');

CREATE POLICY "ext_icons_insert" ON storage.objects
    FOR INSERT WITH CHECK (
        bucket_id = 'extension-icons'
        AND auth.role() IN ('authenticated', 'admin')
    );

CREATE POLICY "ext_icons_update" ON storage.objects
    FOR UPDATE USING (
        bucket_id = 'extension-icons'
        AND auth.role() IN ('authenticated', 'admin')
    );

CREATE POLICY "ext_icons_delete" ON storage.objects
    FOR DELETE USING (
        bucket_id = 'extension-icons'
        AND auth.role() IN ('authenticated', 'admin')
    );

-- Bot photos bucket
DROP POLICY IF EXISTS "bot_photos_select" ON storage.objects;
CREATE POLICY "bot_photos_select" ON storage.objects
    FOR SELECT USING (bucket_id = 'bot-photos');

DROP POLICY IF EXISTS "bot_photos_insert" ON storage.objects;
CREATE POLICY "bot_photos_insert" ON storage.objects
    FOR INSERT WITH CHECK (
        bucket_id = 'bot-photos'
        AND auth.role() IN ('authenticated', 'admin')
    );

DROP POLICY IF EXISTS "bot_photos_update" ON storage.objects;
CREATE POLICY "bot_photos_update" ON storage.objects
    FOR UPDATE USING (
        bucket_id = 'bot-photos'
        AND auth.role() IN ('authenticated', 'admin')
    );

DROP POLICY IF EXISTS "bot_photos_delete" ON storage.objects;
CREATE POLICY "bot_photos_delete" ON storage.objects
    FOR DELETE USING (
        bucket_id = 'bot-photos'
        AND auth.role() IN ('authenticated', 'admin')
    );

-- ==========================================
-- 25. REALTIME PARA HYDRA TEAM
-- ==========================================
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['collab_presence','collab_groups','collab_members','collab_files','collab_runs'] LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = t
        ) THEN
            EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %I', t);
        END IF;
    END LOOP;
END $$;

-- ==========================================
-- 26. ÍNDICES ADICIONALES
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_cloud_projects_email ON cloud_projects (user_email);
CREATE INDEX IF NOT EXISTS idx_project_members_user_email ON project_members (user_email);
CREATE INDEX IF NOT EXISTS idx_hydra_api_keys_user_email ON hydra_api_keys(user_email);
CREATE INDEX IF NOT EXISTS idx_watch_history_email ON user_watch_history(user_email);
CREATE INDEX IF NOT EXISTS idx_continue_watching_email ON user_continue_watching(user_email);
CREATE INDEX IF NOT EXISTS idx_my_list_email ON user_my_list(user_email);
CREATE INDEX IF NOT EXISTS idx_reminders_email ON user_reminders(user_email);
CREATE INDEX IF NOT EXISTS idx_extensions_ext_id ON extensions (ext_id);
CREATE INDEX IF NOT EXISTS idx_extensions_author ON extensions (author_email);
CREATE INDEX IF NOT EXISTS idx_hydra_bots_author_email ON hydra_bots (author_email);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_user ON ai_conversations (user_email);
CREATE INDEX IF NOT EXISTS idx_tickets_user_id ON tickets (user_id);
CREATE INDEX IF NOT EXISTS idx_project_data_lookup ON project_data (project_id, table_name);
CREATE INDEX IF NOT EXISTS idx_collab_members_group ON collab_members (group_id);
CREATE INDEX IF NOT EXISTS idx_collab_members_email ON collab_members (user_email);
CREATE INDEX IF NOT EXISTS idx_collab_files_group ON collab_files (group_id);

-- ==========================================
-- 27. HABILITAR RLS EN TODAS LAS TABLAS  (AL FINAL, ya existen todas)
-- ==========================================
-- Se corre al final para que RLS quede activo en CADA tabla, también en una
-- base nueva (en la versión anterior, correrlo al inicio no cubría las tablas
-- que aún no existían).
DO $$
DECLARE tbl RECORD;
BEGIN
    FOR tbl IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl.tablename);
    END LOOP;
END $$;

-- ==========================================
-- FIN — v7 idempotente. Se puede re-ejecutar cuantas veces quieras.
-- ==========================================
