-- ==========================================================================
-- HYDRA IDE — Servidor SECUNDARIO de Supabase: EXTENSIONES (SIN RLS)
-- Proyecto: gwibpxgibmraqebetvss   (el otro server es SOLO para cuentas)
-- Guarda las extensiones de la comunidad: los usuarios pueden crear/publicar
-- extensiones funcionales (con código, ícono, autor, instalaciones, etc.)
--
-- ▶ Pegá TODO esto en: Supabase (gwibpxgibmraqebetvss) → SQL Editor → Run
-- ==========================================================================

-- ----------------------------------------------------------------------------
-- 1. STORAGE: bucket público para los íconos de las extensiones
-- ----------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('extension-icons', 'extension-icons', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- ----------------------------------------------------------------------------
-- 2. TABLA DE EXTENSIONES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS extensions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    ext_id          TEXT UNIQUE NOT NULL,           -- identificador único (slug)
    name            TEXT NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    readme          TEXT DEFAULT '',                -- HTML/markdown de detalles
    category        TEXT DEFAULT 'Otros',
    version         TEXT DEFAULT '1.0.0',
    icon_url        TEXT,                           -- URL del ícono (storage o externa)
    code            TEXT DEFAULT '',                -- JS que se ejecuta al activar la extensión
    author_user_id  TEXT,
    author_email    TEXT,
    author_username TEXT,
    installs        INTEGER DEFAULT 0,
    rating          NUMERIC DEFAULT 5,
    is_published    BOOLEAN DEFAULT TRUE
);

-- ----------------------------------------------------------------------------
-- 3. ÍNDICES
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_extensions_ext_id      ON extensions (ext_id);
CREATE INDEX IF NOT EXISTS idx_extensions_created_at  ON extensions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_extensions_installs    ON extensions (installs DESC);
CREATE INDEX IF NOT EXISTS idx_extensions_author      ON extensions (author_email);
CREATE INDEX IF NOT EXISTS idx_extensions_category    ON extensions (category);
CREATE INDEX IF NOT EXISTS idx_extensions_published   ON extensions (is_published);

-- ----------------------------------------------------------------------------
-- 4. TRIGGER updated_at AUTOMÁTICO
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_extensions_updated ON extensions;
CREATE TRIGGER trg_extensions_updated
    BEFORE UPDATE ON extensions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ----------------------------------------------------------------------------
-- 5. RPC: contar instalaciones
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION increment_installs(p_ext_id TEXT)
RETURNS void AS $$
BEGIN
    UPDATE extensions SET installs = installs + 1 WHERE ext_id = p_ext_id;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 6. SIN RLS en la tabla (acceso libre con la anon key, como pediste)
-- ----------------------------------------------------------------------------
ALTER TABLE extensions DISABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- 7. STORAGE POLICIES — para poder SUBIR/LEER íconos con la anon key
--    (storage.objects SIEMPRE tiene RLS activado y Supabase no deja apagarlo;
--     por eso se abre con policies permisivas SOLO para el bucket de íconos)
-- ----------------------------------------------------------------------------
DROP POLICY IF EXISTS "ext_icons_select" ON storage.objects;
DROP POLICY IF EXISTS "ext_icons_insert" ON storage.objects;
DROP POLICY IF EXISTS "ext_icons_update" ON storage.objects;
DROP POLICY IF EXISTS "ext_icons_delete" ON storage.objects;

CREATE POLICY "ext_icons_select" ON storage.objects
    FOR SELECT USING (bucket_id = 'extension-icons');

CREATE POLICY "ext_icons_insert" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'extension-icons');

CREATE POLICY "ext_icons_update" ON storage.objects
    FOR UPDATE USING (bucket_id = 'extension-icons');

CREATE POLICY "ext_icons_delete" ON storage.objects
    FOR DELETE USING (bucket_id = 'extension-icons');

-- ----------------------------------------------------------------------------
-- 8. EXTENSIÓN DE EJEMPLO (para probar que carga; podés borrarla luego)
-- ----------------------------------------------------------------------------
INSERT INTO extensions (ext_id, name, description, category, version, author_username, author_email, icon_url, code, readme)
VALUES (
    'hola-mundo',
    'Hola Mundo',
    'Extensión de ejemplo: saluda con un toast y agrega un botón a la barra de estado.',
    'Ejemplo',
    '1.0.0',
    'hydra',
    'hydrasoftwareoficial@gmail.com',
    'https://api.iconify.design/twemoji:waving-hand.svg',
    'hydra.notify("¡Hola desde una extensión de la comunidad! 👋");' ||
    'hydra.addStatusItem("👋 Hola", () => hydra.notify("¡Clic en Hola Mundo!"));',
    '<h3>Hola Mundo</h3><p>Extensión de ejemplo. Al instalarla, muestra un saludo y un botón en la barra de estado.</p>'
)
ON CONFLICT (ext_id) DO NOTHING;

-- ✅ Listo: tabla `extensions` + bucket `extension-icons` + policies de subida.
SELECT 'extensions' AS tabla, COUNT(*) AS total FROM extensions;
