-- ==========================================
-- HYDRA CLOUD & HYDRA PRIME STREAMING - SCHEMA COMPLETO FINAL v6
-- + MARKETPLACE DE EXTENSIONES  (TODO SIN RLS)
-- ==========================================

-- 1. cloud_projects
CREATE TABLE IF NOT EXISTS cloud_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    user_email TEXT NOT NULL,
    project_name TEXT NOT NULL,
    project_type TEXT NOT NULL,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleted', 'provisioning')),
    region TEXT DEFAULT 'us-east-1',
    compute_size TEXT DEFAULT 'micro',
    storage_gb INTEGER DEFAULT 1,
    connection_string TEXT
);

-- 2. deployments
CREATE TABLE IF NOT EXISTS deployments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    user_email TEXT NOT NULL,
    deployment_status TEXT DEFAULT 'pending' CHECK (deployment_status IN ('pending', 'running', 'success', 'failed')),
    commit_hash TEXT,
    logs TEXT
);

-- 3. project_tables
CREATE TABLE IF NOT EXISTS project_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    table_name TEXT NOT NULL,
    description TEXT
);

-- 4. project_auth_users
CREATE TABLE IF NOT EXISTS project_auth_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    provider TEXT DEFAULT 'email',
    last_sign_in_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. project_auth_providers
CREATE TABLE IF NOT EXISTS project_auth_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    provider_name TEXT NOT NULL,
    enabled BOOLEAN DEFAULT false,
    CONSTRAINT unique_project_provider UNIQUE (project_id, provider_name)
);

-- 6. project_auth_policies
CREATE TABLE IF NOT EXISTS project_auth_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    policy_name TEXT NOT NULL,
    table_name TEXT NOT NULL,
    operation TEXT DEFAULT 'SELECT',
    definition TEXT
);

-- 7. project_storage_buckets
CREATE TABLE IF NOT EXISTS project_storage_buckets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    bucket_name TEXT NOT NULL
);

-- 8. project_storage_policies
CREATE TABLE IF NOT EXISTS project_storage_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    policy_name TEXT NOT NULL,
    bucket_name TEXT NOT NULL,
    operation TEXT DEFAULT 'SELECT',
    definition TEXT
);

-- 9. project_members
CREATE TABLE IF NOT EXISTS project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    user_email TEXT NOT NULL,
    role TEXT DEFAULT 'member',
    CONSTRAINT unique_project_member UNIQUE (project_id, user_email)
);

-- 10. project_invitations
CREATE TABLE IF NOT EXISTS project_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    invited_email TEXT NOT NULL,
    invited_by TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined'))
);

-- 11. hydra_api_keys
CREATE TABLE IF NOT EXISTS hydra_api_keys (
    id SERIAL PRIMARY KEY,
    user_email TEXT NOT NULL,
    name TEXT NOT NULL,
    api_key TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_used TIMESTAMP WITH TIME ZONE
);

-- 12. project_edge_functions
CREATE TABLE IF NOT EXISTS project_edge_functions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    function_name TEXT NOT NULL,
    deployment_url TEXT,
    status TEXT DEFAULT 'active'
);

-- 13. project_edge_function_logs
CREATE TABLE IF NOT EXISTS project_edge_function_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    project_id BIGINT REFERENCES cloud_projects(id) ON DELETE CASCADE,
    function_id BIGINT REFERENCES project_edge_functions(id) ON DELETE CASCADE,
    log_message TEXT NOT NULL
);

-- ==========================================
-- TABLAS PARA EL HISTORIAL DE HYDRA PRIME (Con JSONB)
-- ==========================================
CREATE TABLE IF NOT EXISTS user_streaming_profiles (
    user_email TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    preferred_server TEXT DEFAULT 'UNLIMPLAY',
    theme TEXT DEFAULT 'dark'
);

CREATE TABLE IF NOT EXISTS user_watch_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    item_id TEXT NOT NULL,
    item_data JSONB NOT NULL,
    watched_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_history_item UNIQUE (user_email, item_id)
);

CREATE TABLE IF NOT EXISTS user_continue_watching (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    item_id TEXT NOT NULL,
    item_data JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_continue_item UNIQUE (user_email, item_id)
);

CREATE TABLE IF NOT EXISTS user_my_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    item_id TEXT NOT NULL,
    item_data JSONB NOT NULL,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_mylist_item UNIQUE (user_email, item_id)
);

CREATE TABLE IF NOT EXISTS user_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    item_id TEXT NOT NULL,
    item_data JSONB NOT NULL,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_reminder_item UNIQUE (user_email, item_id)
);

-- ==========================================
-- 14. MARKETPLACE DE EXTENSIONES (HYDRA IDE)
-- ==========================================

-- Bucket público para los íconos de las extensiones
INSERT INTO storage.buckets (id, name, public)
VALUES ('extension-icons', 'extension-icons', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Tabla de extensiones
CREATE TABLE IF NOT EXISTS extensions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    ext_id          TEXT UNIQUE NOT NULL,
    name            TEXT NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    readme          TEXT DEFAULT '',
    category        TEXT DEFAULT 'Otros',
    version         TEXT DEFAULT '1.0.0',
    icon_url        TEXT,
    code            TEXT DEFAULT '',
    author_user_id  TEXT,
    author_email    TEXT,
    author_username TEXT,
    installs        INTEGER DEFAULT 0,
    rating          NUMERIC DEFAULT 5,
    is_published    BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_extensions_ext_id     ON extensions (ext_id);
CREATE INDEX IF NOT EXISTS idx_extensions_created_at ON extensions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_extensions_installs   ON extensions (installs DESC);
CREATE INDEX IF NOT EXISTS idx_extensions_author     ON extensions (author_email);
CREATE INDEX IF NOT EXISTS idx_extensions_category   ON extensions (category);
CREATE INDEX IF NOT EXISTS idx_extensions_published  ON extensions (is_published);

-- Trigger updated_at automático (para la tabla de extensiones)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_extensions_updated ON extensions;
CREATE TRIGGER trg_extensions_updated
    BEFORE UPDATE ON extensions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- RPC: contar instalaciones
CREATE OR REPLACE FUNCTION increment_installs(p_ext_id TEXT)
RETURNS void AS $$
BEGIN
    UPDATE extensions SET installs = installs + 1 WHERE ext_id = p_ext_id;
END;
$$ LANGUAGE plpgsql;

-- Extensión de ejemplo (podés borrarla luego)
INSERT INTO extensions (ext_id, name, description, category, version, author_username, author_email, icon_url, code, readme)
VALUES (
    'hola-mundo',
    'Hola Mundo',
    'Extensión de ejemplo: saluda con un toast y agrega un botón a la barra de estado.',
    'Ejemplo', '1.0.0', 'hydra', 'hydrasoftwareoficial@gmail.com',
    'https://api.iconify.design/lucide:box.svg',
    'hydra.notify("Hola desde una extensión de la comunidad.");hydra.addStatusItem("Hola", () => hydra.notify("Clic en Hola Mundo."));',
    '<h3>Hola Mundo</h3><p>Extensión de ejemplo. Al instalarla, muestra un aviso y un botón en la barra de estado.</p>'
)
ON CONFLICT (ext_id) DO NOTHING;

-- ==========================================
-- ÍNDICES DE OPTIMIZACIÓN (A PRUEBA DE FALLOS)
-- ==========================================
DO $$
BEGIN
    -- 1. Inyectamos las columnas si las tablas viejas no las tenían
    ALTER TABLE IF EXISTS cloud_projects ADD COLUMN IF NOT EXISTS user_email TEXT;
    ALTER TABLE IF EXISTS deployments ADD COLUMN IF NOT EXISTS user_email TEXT;
    ALTER TABLE IF EXISTS project_members ADD COLUMN IF NOT EXISTS user_email TEXT;
    ALTER TABLE IF EXISTS hydra_api_keys ADD COLUMN IF NOT EXISTS user_email TEXT;

    ALTER TABLE IF EXISTS user_streaming_profiles ADD COLUMN IF NOT EXISTS user_email TEXT;
    ALTER TABLE IF EXISTS user_watch_history ADD COLUMN IF NOT EXISTS user_email TEXT;
    ALTER TABLE IF EXISTS user_continue_watching ADD COLUMN IF NOT EXISTS user_email TEXT;
    ALTER TABLE IF EXISTS user_my_list ADD COLUMN IF NOT EXISTS user_email TEXT;
    ALTER TABLE IF EXISTS user_reminders ADD COLUMN IF NOT EXISTS user_email TEXT;

    -- 2. Ahora sí, creamos los índices sin que explote
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_cloud_projects_email ON cloud_projects (user_email)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_members_user_email ON project_members (user_email)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_hydra_api_keys_user_email ON hydra_api_keys(user_email)';

    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_tables_project_id ON project_tables (project_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_auth_users_project_id ON project_auth_users (project_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_auth_providers_project_id ON project_auth_providers (project_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_auth_policies_project_id ON project_auth_policies (project_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_storage_buckets_project_id ON project_storage_buckets (project_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_storage_policies_project_id ON project_storage_policies (project_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_members_project_id ON project_members (project_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_invitations_project_id ON project_invitations (project_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_edge_functions_project_id ON project_edge_functions(project_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_project_edge_function_logs_project_id ON project_edge_function_logs(project_id)';

    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_watch_history_email ON user_watch_history(user_email)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_continue_watching_email ON user_continue_watching(user_email)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_my_list_email ON user_my_list(user_email)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_reminders_email ON user_reminders(user_email)';
END $$;

-- ==========================================
-- DESHABILITAR RLS EN TODAS LAS TABLAS DEL ESQUEMA PUBLIC
-- (incluye automáticamente la tabla `extensions`)
-- ==========================================
DO $$
DECLARE tbl RECORD;
BEGIN
    FOR tbl IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
        EXECUTE format('ALTER TABLE %I DISABLE ROW LEVEL SECURITY', tbl.tablename);
    END LOOP;
END $$;

-- ==========================================
-- STORAGE POLICIES PARA EL BUCKET DE ÍCONOS
-- (storage.objects SIEMPRE tiene RLS y no se puede apagar; se abre con policies
--  permisivas SOLO para el bucket 'extension-icons')
-- ==========================================
DROP POLICY IF EXISTS "ext_icons_select" ON storage.objects;
DROP POLICY IF EXISTS "ext_icons_insert" ON storage.objects;
DROP POLICY IF EXISTS "ext_icons_update" ON storage.objects;
DROP POLICY IF EXISTS "ext_icons_delete" ON storage.objects;

CREATE POLICY "ext_icons_select" ON storage.objects
    FOR SELECT USING (bucket_id = 'extension-icons');
CREATE POLICY "ext_icons_insert" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'extension-icons');
CREATE POLICY "ext_icons_update" ON storage.objects
    FOR UPDATE USING (bucket_id = 'extension-icons');
CREATE POLICY "ext_icons_delete" ON storage.objects
    FOR DELETE USING (bucket_id = 'extension-icons');
